export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  NO_HOTELS_FOUND: 'NO_HOTELS_FOUND',
  ALL_SUPPLIERS_FAILED: 'ALL_SUPPLIERS_FAILED',
  SEARCH_TIMEOUT: 'SEARCH_TIMEOUT',
  SEARCH_CANCELLED: 'SEARCH_CANCELLED',
  SEARCH_PENDING: 'SEARCH_PENDING',
  ORCHESTRATOR_UNAVAILABLE: 'ORCHESTRATOR_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const ErrorHttpStatus: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  PAYLOAD_TOO_LARGE: 413,
  RATE_LIMITED: 429,
  NO_HOTELS_FOUND: 200,
  ALL_SUPPLIERS_FAILED: 502,
  SEARCH_TIMEOUT: 504,
  SEARCH_CANCELLED: 499,
  SEARCH_PENDING: 202,
  ORCHESTRATOR_UNAVAILABLE: 503,
  INTERNAL_ERROR: 500,
};
